### ISSUE TITLE
Linux app crashing when opening "Guest Apps" tab

### ISSUE THREAD

**Issue by chqoot-vgxu** [casualsnek/cassowary#17]
The windows server seems to return a list of app with at least one None value inside.
Tested on versions alpha, 0.2 and 0.3 with windows in a qemu vm.

Logs:
```
$ python3 -m cassowary -a
[ 2022-01-24 22:01:35,655 ] | [  DEBUG ] :  [    __init__ ->                 main  ] -->  Starting configuration GUI 
[ 2022-01-24 22:01:35,822 ] | [  DEBUG ] :  [      helper ->              vm_wake  ] -->  VM is not suspended..  
[ 2022-01-24 22:01:35,822 ] | [  DEBUG ] :  [     main_ui ->          __reconnect  ] -->  Tring to start a RDP session for server side component to start ! 
[ 2022-01-24 22:01:35,822 ] | [  DEBUG ] :  [     main_ui ->          __reconnect  ] -->  Waiting for session startup process to terminate  
[22:01:35:801] [45065:45066] [INFO][com.freerdp.core] - freerdp_connect:freerdp_set_last_error_ex resetting error state
[22:01:35:801] [45065:45066] [INFO][com.freerdp.client.common.cmdline] - loading channelEx rdpdr
[22:01:35:801] [45065:45066] [INFO][com.freerdp.client.common.cmdline] - loading channelEx rdpsnd
[22:01:35:801] [45065:45066] [INFO][com.freerdp.client.common.cmdline] - loading channelEx cliprdr
[22:01:35:801] [45065:45066] [INFO][com.freerdp.client.common.cmdline] - loading channelEx rail
[22:01:35:801] [45065:45066] [INFO][com.freerdp.client.common.cmdline] - loading channelEx drdynvc
[22:01:36:112] [45065:45066] [INFO][com.freerdp.primitives] - primitives autodetect, using optimized
[22:01:36:115] [45065:45066] [INFO][com.freerdp.core] - freerdp_tcp_is_hostname_resolvable:freerdp_set_last_error_ex resetting error state
[22:01:36:115] [45065:45066] [INFO][com.freerdp.core] - freerdp_tcp_connect:freerdp_set_last_error_ex resetting error state
[22:01:36:120] [45065:45066] [WARN][com.freerdp.core.nego] - Error: SSL_NOT_ALLOWED_BY_SERVER
[22:01:36:120] [45065:45066] [INFO][com.freerdp.core] - freerdp_tcp_is_hostname_resolvable:freerdp_set_last_error_ex resetting error state
[22:01:36:120] [45065:45066] [INFO][com.freerdp.core] - freerdp_tcp_connect:freerdp_set_last_error_ex resetting error state
[22:01:36:125] [45065:45066] [WARN][com.freerdp.core.nego] - Error: SSL_NOT_ALLOWED_BY_SERVER
[22:01:36:125] [45065:45066] [INFO][com.freerdp.core] - freerdp_tcp_is_hostname_resolvable:freerdp_set_last_error_ex resetting error state
[22:01:36:125] [45065:45066] [INFO][com.freerdp.core] - freerdp_tcp_connect:freerdp_set_last_error_ex resetting error state
[22:01:37:436] [45065:45066] [INFO][com.freerdp.gdi] - Local framebuffer format  PIXEL_FORMAT_BGRX32
[22:01:37:436] [45065:45066] [INFO][com.freerdp.gdi] - Remote framebuffer format PIXEL_FORMAT_RGB16
[22:01:37:442] [45065:45066] [INFO][com.winpr.clipboard] - initialized POSIX local file subsystem
[22:01:37:444] [45065:45066] [INFO][com.freerdp.channels.rdpsnd.client] - [static] Loaded fake backend for rdpsnd
[22:01:37:444] [45065:45084] [INFO][com.freerdp.channels.rdpdr.client] - Loading device service drive [root] (static)
[22:01:37:444] [45065:45066] [INFO][com.freerdp.channels.drdynvc.client] - Loading Dynamic Virtual Channel disp
[22:01:37:502] [45065:45084] [INFO][com.freerdp.channels.rdpdr.client] - registered device #1: root (type=8 id=1)
[22:01:37:728] [45065:45066] [WARN][com.freerdp.client.x11] - xf_Pointer: Invalid appWindow
[22:01:37:745] [45065:45066] [WARN][com.freerdp.client.x11] - xf_Pointer: Invalid appWindow
[22:01:37:757] [45065:45086] [ERROR][com.freerdp.client.x11] - RAIL exec error: execResult=RAIL_EXEC_E_FAIL NtError=0x2

[22:01:37:757] [45065:45066] [ERROR][com.freerdp.core] - freerdp_check_fds() failed - 0
[22:01:37:757] [45065:45066] [INFO][com.freerdp.client.common] - Network disconnect!
[22:01:37:757] [45065:45066] [ERROR][com.freerdp.client.x11] - Failed to check FreeRDP file descriptor
[ 2022-01-24 22:01:37,827 ] | [  DEBUG ] :  [     main_ui ->          __reconnect  ] -->  Session startup process completed. 
Trying to reconnect
[ 2022-01-24 22:01:37,828 ] | [   INFO ] :  [      client ->      init_connection  ] -->  Attempting to connect to server 
[ 2022-01-24 22:01:37,829 ] | [   INFO ] :  [      client ->      init_connection  ] -->  Connected to server at 192.168.122.236:7220 
[ 2022-01-24 22:01:37,829 ] | [  DEBUG ] :  [      client ->      init_connection  ] -->  Starting sender and receiver threads 
[ 2022-01-24 22:01:42,086 ] | [  DEBUG ] :  [      client ->               __send  ] -->  Sending message to server 
[ 2022-01-24 22:01:42,996 ] | [  DEBUG ] :  [      client ->               __send  ] -->  Sending message to server 
Traceback (most recent call last):
  File "/home/zane/.local/lib/python3.10/site-packages/cassowary/gui/components/main_ui.py", line 208, in __tab_changed
    self.populate_applications()
  File "/home/zane/.local/lib/python3.10/site-packages/cassowary/gui/components/main_ui.py", line 339, in populate_applications
    name = app[0].split(":")[0]
AttributeError: 'NoneType' object has no attribute 'split'
[1]    45055 abort (core dumped)  python3 -m cassowary -a
```

**Comment by casualsnek** [comment]
Thank you for reporting, i will make a commit soon that will fix this problem !

**Comment by chqoot-vgxu** [comment]
I did some testing, apparently for one app (wt), it returns None for both description and version, hence the crash. I don't know if it's my VM broken nor if it's fixable in some way

**Comment by casualsnek** [comment]
> I did some testing, apparently for one app (wt), it returns None for both description and version, hence the crash. I don't know if it's my VM broken nor if it's fixable in some way.
> 
> EDIT: I disinstalled wt and that fixed it, probably a problem on my side, closing

I see you closed the issue, but after the latest release this error should be handled properly and should not result in a crash ! :)

**Comment by chqoot-vgxu** [comment]
Good to know! I closed it because I thought it was a problem with my machine, maybe one of the cleanup scripts that I tried deleted the wrong file/registry key
