### ISSUE TITLE
Cannot open Cassowary 

### ISSUE THREAD

**Issue by XtremeMusic2** [casualsnek/cassowary#19]
Hello, I am using Pop OS and for some reason I cannot start Cassowary. Here is the output of python -m cassowary -a
```
 2022-01-30 02:33:58,355 ] | [  DEBUG ] :  [    __init__ ->                 main  ] -->  Starting configuration GUI 
error: Failed to get option 'domain': Option argument is empty
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/xtrememusic/.local/lib/python3.9/site-packages/cassowary/__main__.py", line 4, in <module>
    main()
  File "/home/xtrememusic/.local/lib/python3.9/site-packages/cassowary/__init__.py", line 154, in main
    mainui = MainWindow()
  File "/home/xtrememusic/.local/lib/python3.9/site-packages/cassowary/gui/components/main_ui.py", line 30, in __init__
    self.__reconnect(no_popup=True)
  File "/home/xtrememusic/.local/lib/python3.9/site-packages/cassowary/gui/components/main_ui.py", line 151, in __reconnect
    vm_wake()
  File "/home/xtrememusic/.local/lib/python3.9/site-packages/cassowary/base/helper.py", line 259, in vm_wake
    vms = subprocess.check_output(["virsh", "domstate", cfgvars.config["vm_name"]])
  File "/usr/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['virsh', 'domstate', '']' returned non-zero exit status 1.
```

**Comment by casualsnek** [comment]
> Hello, I am using Pop OS and for some reason I cannot start Cassowary. Here is the output of python -m cassowary -a
> 
> 2022-01-30 02:33:58,355 ] | [ DEBUG ] : [ **init** -> main ] --> Starting configuration GUI error: Failed to get option 'domain': Option argument is empty Traceback (most recent call last): File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main return _run_code(code, main_globals, None, File "/usr/lib/python3.9/runpy.py", line 87, in _run_code exec(code, run_globals) File "/home/xtrememusic/.local/lib/python3.9/site-packages/cassowary/**main**.py", line 4, in main() File "/home/xtrememusic/.local/lib/python3.9/site-packages/cassowary/**init**.py", line 154, in main mainui = MainWindow() File "/home/xtrememusic/.local/lib/python3.9/site-packages/cassowary/gui/components/main_ui.py", line 30, in **init** self.__reconnect(no_popup=True) File "/home/xtrememusic/.local/lib/python3.9/site-packages/cassowary/gui/components/main_ui.py", line 151, in __reconnect vm_wake() File "/home/xtrememusic/.local/lib/python3.9/site-packages/cassowary/base/helper.py", line 259, in vm_wake vms = subprocess.check_output(["virsh", "domstate", cfgvars.config["vm_name"]]) File "/usr/lib/python3.9/subprocess.py", line 424, in check_output return run(*popenargs, stdout=PIPE, timeout=timeout, check=True, File "/usr/lib/python3.9/subprocess.py", line 528, in run raise CalledProcessError(retcode, process.args, subprocess.CalledProcessError: Command '['virsh', 'domstate', '']' returned non-zero exit status 1.

I am currently working on fixing this issue and few other, should be fixed in next update ! You can try running older release while this gets fixed !

**Comment by hwak722** [comment]
Can you update to release v0.4 and try if it fixes this issue ?

**Comment by XtremeMusic2** [comment]
it did fix the problem
