### ISSUE TITLE
A little bit narrow

### ISSUE THREAD

**Issue by bphd** [casualsnek/cassowary#97]
![image](https://user-images.githubusercontent.com/10251866/183307481-7c696b86-23fb-48ae-b936-80bc3436955a.png)

And it's worse when widened

![image](https://user-images.githubusercontent.com/10251866/183307502-3bf4d3b0-1ccb-404f-9e86-876361cbde02.png)

To reproduce, you just have to `cassowary -a`

And besides, it's totally not intuitive if you begin your journey by installing from AUR. No instructions at all. I've went to the manual and found something talking about GUI. I said why not. Then I was stuck in a window telling me that a connection to an IP was timed out, considering that I still haven't configured anything, it's kind of weird. At least if both this message and the configuration panel can be openend at the same time, it would have been less confusing

**Describe the bug**
A Description of what the bug is.

**To Reproduce**

**Expected behavior**

**Screenshots**

**System information:**
 - Cassowary Linux client version: [run ```python3 -m cassowary -h``` to find version ]
 - Cassowary windows component version: [run ```"C:\Program Files\cassowary\cassowary.exe" -h``` to find version]
 - Linux Distribution: [e.g. Arch Linux]
 - Windows/Edition used [e.g. 10/enterprise, 7/ultimate]

**Additional context**

**Comment by casualsnek** [comment]
Thank you for filing the issue, the AUR package is not maintained by me and some people have issues setting up cassowary without the instructions presented in GitHub !

The connection should not have begun if no IP address was configured and i will look into the issue.
For the layout issue, can be please share the version of PyQt installed on your system. 
And also share the log files if they have been created !

**Comment by bphd** [comment]
python-pyqt6 6.3.1-1
python-pyqt5 5.15.7-1
python-qtpy 2.1.0-1

**Comment by casualsnek** [comment]
> python-pyqt6 6.3.1-1 python-pyqt5 5.15.7-1 python-qtpy 2.1.0-1
> 
> I don't know if Cassowary produces log files I don't find any unit or user-unit related to Cassowary

Log file should be at ```/home/$USER/.config/caualrdh/``` on linux 
and
```%userprofile%/.config/caualrdh/``` on windows system

**Comment by bphd** [comment]
The contents of this logfile

``` log
client_.init_connection()
ConnectionResetError: [Errno 104] Connection reset by peer
[] | [ DEBUG ] : [ client -> init_connection ] --> Starting sender and receiver threads 
[] | [ DEBUG ] : [ client -> __receive ] --> Stopping receive sub-threadd... (True) 
[] | [ DEBUG ] : [ client -> __send ] --> Sending message to server 
[] | [ DEBUG ] : [ client -> __send ] --> Stopping send sub-thread.d... (True) 
[] | [ DEBUG ] : [ helper -> fix_black_window ] --> An app was already opened, the black window should not appear now ! 
[] | [ DEBUG ] : [ helper -> fix_black_window ] --> App window seems to be created or timeout. Creating marker & Waiting 2 seconds - . 
[] | [ DEBUG ] : [ helper -> fix_black_window ] --> Created a marker -> One session done 
[] | [ DEBUG ] : [ helper -> fix_black_window ] --> Opening & closing a test window to trigger login or try to fix black screen bug on first launch 
[] | [ DEBUG ] : [ helper -> fix_black_window ] --> Test window opened and closed ! 
[] | [ DEBUG ] : [ helper -> fix_black_window ] --> Trying to fix black window bug by opening a test window before requested application - .CMDLINE: xfreerdp /d:"" /u:"" /p:"Edit It Yourself" /v:"192.168.1.1" +clipboard /a:drive,root,/ +decorations /cert-ignore /sound /scale:100 /dynamic-resolution /span /wm-class:"cassowaryApp-echo" /app:"ipconfig.exe" 
[] | [ DEBUG ] : [ helper -> fix_black_window ] --> Trying to fix black window bug by opening a test window before requested application - .CMDLINE: xfreerdp /d:"" /u:"" /p:"" /v:"" +clipboard /a:drive,root,/ +decorations /cert-ignore /sound /scale:100 /dynamic-resolution /span /wm-class:"cassowaryApp-echo" /app:"ipconfig.exe" 
[] | [ DEBUG ] : [ helper -> full_rdp ] --> Creating a full RDP session with commandline : {rdc} /d:"{domain}" /u:"{user}" /p:"{passd}" /v:{ip} /a:drive,root,{share_root} +auto-reconnect +clipboard /cert-ignore /audio-mode:1 /scale:{scale} /wm-class:"cassowaryApp-FULLSESSION" /dynamic-resolution /{mflag} {rdflag} 1> /dev/null 2>&1 & 
[] | [ DEBUG ] : [ helper -> full_rdp ] --> Full RDP session ended ! 
[] | [ DEBUG ] : [ helper -> vm_suspension_handler ] --> disabled 
[] | [ DEBUG ] : [ helper -> vm_suspension_handler ] --> Refreshing config to update to probable config changes ! 
[] | [ DEBUG ] : [ helper -> vm_suspension_handler ] --> VM watcher active ! 
[] | [ DEBUG ] : [ helper -> vm_wake ] --> Attempting to resume VM 
[] | [ DEBUG ] : [ helper -> vm_wake ] --> VM name is blank, maybe not a vm skipping vm resume process ! 
[] | [ DEBUG ] : [ __init__ -> main ] --> Starting configuration GUI 
[] | [ DEBUG ] : [ main_ui -> __reconnect ] --> Forced reconnection attempt, no active application or explicitly forced 
dom = conn.lookupByName(cfgvars.config["vm_name"])
dom = conn.lookupByName(name)
[] | [ ERROR ] : [ client -> __receive ] --> Error receiving messages, Exception- [Errno 104] Connection reset by peer, Traceback : Traceback (most recent call last):
[] | [ ERROR ] : [ helper -> ip_by_vm_name ] --> Cannot get ip for '' -> Traceback (most recent call last):
[] | [ ERROR ] : [ helper -> vm_wake ] --> Could not suspend vm '' -> Traceback (most recent call last):
[] | [ ERROR ] : [ __init__ -> start_bg_client ] --> Ignored exception: 'Traceback (most recent call last):
File "/usr/lib/python3.10/site-packages/cassowary/base/helper.py", line 35, in ip_by_vm_name
File "/usr/lib/python3.10/site-packages/cassowary/base/helper.py", line 392, in vm_wake
File "/usr/lib/python3.10/site-packages/cassowary/client.py", line 50, in init_connection
File "/usr/lib/python3.10/site-packages/cassowary/client.py", line 68, in __receive
File "/usr/lib/python3.10/site-packages/cassowary/__init__.py", line 31, in start_bg_client
File "/usr/lib/python3.10/site-packages/libvirt.py", line 4942, in lookupByName
[] | [ INFO ] : [ client -> init_connection ] --> Attempting to connect to server 
[] | [ INFO ] : [ client -> init_connection ] --> Connected to server at :7220 
[] | [ INFO ] : [ __init__ -> start_bg_client ] --> Connecting to server.... 
libvirt.libvirtError: Domain not found: no domain with matching name ''
OSError: [Errno 113] No route to host
raise libvirtError('virDomainLookupByName() failed')
recent_msg = self.server.recv(16000)
', reconnecting to server after 5 seconds 
self.server.connect((self.__host, self.__port))
[] | [ WARNING ] : [ helper -> ip_by_vm_name ] --> Could not get proper ip address for domain ''
```

**Comment by bphd** [comment]
Logs of the guest

[] | [ DEBUG ] : [ cmd_dirs -> __get_shared_drives ] --> Getting shared local drives using net share 
[] | [ DEBUG ] : [ cmd_dirs -> __init__ ] --> Looks like this is not a RDP session, share for root folder not found 
[] | [ DEBUG ] : [ server -> __init__ ] --> [ClientID:\] New client connected 
[] | [ DEBUG ] : [ server -> __receive ] --> [ClientID:\] Receiver is exiting 
[] | [ DEBUG ] : [ server -> __send ] --> [ClientID:\] Got message in queue. MSG_ID:
[] | [ DEBUG ] : [ server -> __send ] --> [ClientID:\] Sender is exiting 
[] | [ DEBUG ] : [ server -> start_server ] --> Client Thread '' has stopped listening, removing it 
[] | [ ERROR ] : [ server -> __receive ] --> [ClientID:\] Received a deformed message. Message body : 'b'{"id": "", "type": "request", "command": ["get-drive-shares"]}~~!enm!~~{"id": "", "type": "request", "command": ["get-installed-apps"]}~~!enm!~~'', Traceback : Traceback (most recent call last):
 File "json\decoder.py", line 340, in decode
 File "json\__init__.py", line 348, in loads
 File "server.py", line 115, in __receive
[] | [ INFO ] : [ server -> __receive ] --> [ClientID:\] Received a request : MSG_ID:
[] | [ INFO ] : [ server -> __receive ] --> [ClientID:\] Request handled by : dircommands 
[] | [ INFO ] : [ server -> __receive ] --> [ClientID:\] Request handled by : generalcommands 
[] | [ INFO ] : [ server -> __send ] --> [ClientID:\] Sent message to client. MSG_ID:
json.decoder.JSONDecodeError: Extra data: line 1 column 67 (char 66)
